#!/bin/sh
#SBATCH --time=3-00:00:00
#SBATCH --error=job.%J.err
#SBATCH --gres=gpu:2

cd /scratch/amitsethi/Group_loss/UCF
module unload gcc/5.2.0
module load boost/cdac/gcc/4.8.2/boost-1.55
module load cuda75/blas/7.5.18
rm -rf output.txt
python groupLossCNN.py > output.txt

